export const Members = [
  {
    name: "John Doe",
    image: "https://example.com/images/john_doe.jpg",
    country: "USA",
    age: 34,
    membership: "Gold",
    accumendation: "Excellent Performance",
    summit_member: "Jane Smith",
    capital: "Washington, D.C.",
  },
  {
    name: "Jane Smith",
    image: "https://example.com/images/jane_smith.jpg",
    country: "Canada",
    age: 28,
    membership: "Silver",
    accumendation: "Outstanding Contributor",
    summit_member: "Ali Khan",
    capital: "Ottawa",
  },
  {
    name: "Ali Khan",
    image: "https://example.com/images/ali_khan.jpg",
    country: "Pakistan",
    age: 40,
    membership: "Platinum",
    accumendation: "Top Performer",
    summit_member: "Maria Gonzalez",
    capital: "Islamabad",
  },
  {
    name: "Maria Gonzalez",
    image: "https://example.com/images/maria_gonzalez.jpg",
    country: "Mexico",
    age: 26,
    membership: "Bronze",
    accumendation: "Rising Star",
    summit_member: "John Doe",
    capital: "Mexico City",
  },
  {
    name: "David Williams",
    image: "https://example.com/images/david_williams.jpg",
    country: "UK",
    age: 45,
    membership: "Diamond",
    accumendation: "Leadership Excellence",
    summit_member: "Sophia Liu",
    capital: "London",
  },
  {
    name: "Sophia Liu",
    image: "https://example.com/images/sophia_liu.jpg",
    country: "China",
    age: 38,
    membership: "Gold",
    accumendation: "Innovative Thinker",
    summit_member: "David Williams",
    capital: "Beijing",
  },
  {
    name: "Carlos Ramirez",
    image: "https://example.com/images/carlos_ramirez.jpg",
    country: "Spain",
    age: 30,
    membership: "Silver",
    accumendation: "Creative Visionary",
    summit_member: "Elena Perez",
    capital: "Madrid",
  },
  {
    name: "Elena Perez",
    image: "https://example.com/images/elena_perez.jpg",
    country: "Argentina",
    age: 33,
    membership: "Bronze",
    accumendation: "Exceptional Skill",
    summit_member: "Carlos Ramirez",
    capital: "Buenos Aires",
  },
  {
    name: "Ahmed Al-Farsi",
    image: "https://example.com/images/ahmed_al_farsi.jpg",
    country: "UAE",
    age: 50,
    membership: "Platinum",
    accumendation: "Strategic Leader",
    summit_member: "Fatima Al-Nasser",
    capital: "Abu Dhabi",
  },
  {
    name: "Fatima Al-Nasser",
    image: "https://example.com/images/fatima_al_nasser.jpg",
    country: "Qatar",
    age: 29,
    membership: "Gold",
    accumendation: "Visionary Innovator",
    summit_member: "Ahmed Al-Farsi",
    capital: "Doha",
  },
];
