export const stateOptions = [
  { value: "al", label: "Alabama (AL)" },
  { value: "ak", label: "Alaska (AK)" },
  { value: "ab", label: "Alberta (CAN)" },
  { value: "az", label: "Arizona (AZ)" },
  { value: "ar", label: "Arkansas (AR)" },
  { value: "bc", label: "British Columbia (CAN)" },
  { value: "ca", label: "California (CA)" },
  { value: "co", label: "Colorado (CO)" },
  { value: "ct", label: "Connecticut (CT)" },
  { value: "de", label: "Delaware (DE)" },
  { value: "dc", label: "District of Columbia (DC)" },
  { value: "fl", label: "Florida (FL)" },
  { value: "ga", label: "Georgia (GA)" },
  { value: "hi", label: "Hawaii (HI)" },
  { value: "id", label: "Idaho (ID)" },
  { value: "il", label: "Illinois (IL)" },
  { value: "in", label: "Indiana (IN)" },
  { value: "ia", label: "Iowa (IA)" },
  { value: "ks", label: "Kansas (KS)" },
  { value: "ky", label: "Kentucky (KY)" },
  { value: "lb", label: "Labrador (CAN)" },
  { value: "la", label: "Louisiana (LA)" },
  { value: "me", label: "Maine (ME)" },
  { value: "mb", label: "Manitoba (CAN)" },
  { value: "md", label: "Maryland (MD)" },
  { value: "ma", label: "Massachusetts (MA)" },
  { value: "mi", label: "Michigan (MI)" },
  { value: "mn", label: "Minnesota (MN)" },
  { value: "ms", label: "Mississippi (MS)" },
  { value: "mo", label: "Missouri (MO)" },
  { value: "mt", label: "Montana (MT)" },
  { value: "ne", label: "Nebraska (NE)" },
  { value: "nv", label: "Nevada (NV)" },
  { value: "nb", label: "New Brunswick (CAN)" },
  { value: "nh", label: "New Hampshire (NH)" },
  { value: "nj", label: "New Jersey (NJ)" },
  { value: "nm", label: "New Mexico (NM)" },
  { value: "ny", label: "New York (NY)" },
  { value: "nl", label: "Newfoundland (CAN)" },
  { value: "nc", label: "North Carolina (NC)" },
  { value: "nd", label: "North Dakota (ND)" },
  { value: "nt", label: "Northwest Territories (CAN)" },
  { value: "ns", label: "Nova Scotia (CAN)" },
  { value: "nu", label: "Nunavut (CAN)" },
  { value: "oh", label: "Ohio (OH)" },
  { value: "ok", label: "Oklahoma (OK)" },
  { value: "on", label: "Ontario (CAN)" },
  { value: "or", label: "Oregon (OR)" },
  { value: "pa", label: "Pennsylvania (PA)" },
  { value: "pe", label: "Prince Edward Island (CAN)" },
  { value: "qc", label: "Quebec (CAN)" },
  { value: "ri", label: "Rhode Island (RI)" },
  { value: "sk", label: "Saskatchewan (CAN)" },
  { value: "sc", label: "South Carolina (SC)" },
  { value: "sd", label: "South Dakota (SD)" },
  { value: "tn", label: "Tennessee (TN)" },
  { value: "tx", label: "Texas (TX)" },
  { value: "ut", label: "Utah (UT)" },
  { value: "vt", label: "Vermont (VT)" },
  { value: "va", label: "Virginia (VA)" },
  { value: "wa", label: "Washington (WA)" },
  { value: "wv", label: "West Virginia (WV)" },
  { value: "wi", label: "Wisconsin (WI)" },
  { value: "wy", label: "Wyoming (WY)" },
  { value: "yt", label: "Yukon (CAN)" },
];

export const getStateLabel = (stateValue: string) => {
  const state = stateOptions.find((option) => option.value == stateValue);
  return state?.label ? state.label : "N/A";
};
